### ISSUE TITLE
OPENAI ERR: 

### ISSUE THREAD

**Issue by ronykhanking1** [notunderctrl/gpt-3.5-chat-bot#2]
The bot is online!
OPENAI ERR: Error: Request failed with status code 429
ERR: TypeError: Cannot read properties of undefined (reading 'data')

**Comment by notunderctrl** [comment]
Based on my experience this error occurs on accounts with free trials. Error 429 generally means you're being rate limited (which could be the case), but more so I've experience this error when either the free trial balance is fully used up or if it's a brand new OpenAI account.

Three possible fixes to this problem:
- Switch to a paid plan - In my experience this resolves it within 5-10 minutes.
- Try getting in contact with customer support
- Create a new OpenAI account
