### ISSUE TITLE
I have a error in replit.com

### ISSUE THREAD

**Issue by SohamRoy20Gaming** [notunderctrl/gpt-3.5-chat-bot#4]
Error :-
![Screenshot_20230414-165203~2](https://user-images.githubusercontent.com/109818645/232031353-d8d23df2-b0a6-4146-9399-69a0584320da.png)

**Comment by notunderctrl** [comment]
Error 429 means your OpenAI account is being rate limited. You may be sending too many requests. You can fix that by upgrading to a paid plan.

**Comment by SohamRoy20Gaming** [comment]
I didn't change the code for "too many requests"

**Comment by SohamRoy20Gaming** [comment]
I am basic discord bot maker so i didn't pay money for this things
